version: "3,8"

services:
  app:
    build: .
    container_name: task_tracker_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - network
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

networks:
  network:
    external: true
    name: test-task-for-junior-backend-developer_default
