"""Initial migration

Revision ID: f99c1839a3f4
Revises: 
Create Date: 2026-04-10 00:02:02.316775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f99c1839a3f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_templates',
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('rule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('target_date', sa.Date(), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tasks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_target_date'), 'tasks', ['target_date'], unique=False)
    op.create_index(op.f('ix_tasks_template_id'), 'tasks', ['template_id'], unique=False)
    op.create_unique_constraint('uq_task_template_date', 'tasks', ['template_id', 'target_date'])
    op.create_foreign_key(None, 'tasks', 'task_templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint('uq_task_template_date', 'tasks', type_='unique')
    op.drop_index(op.f('ix_tasks_template_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_target_date'), table_name='tasks')
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('tasks', 'target_date')
    op.drop_column('tasks', 'template_id')
    op.drop_table('task_templates')
    # ### end Alembic commands ###
